
version: '2'

services:
  db:
    image: mariadb
    volumes:
      - db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
    networks:
      - db
  wordpress:
    image: wordpress:4.7.2
    depends_on:
      - db
    volumes:
      - ./plugins:/var/www/html/wp-content/plugins
      - theme:/var/www/html/wp-content/themes/default
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_PASSWORD: password
    networks:
      - db
      - wp
  dev:
    build: .
    image: wordpress-sucks:0.0.1
    volumes:
      - ./theme:/theme
      - theme:/wp-content/themes/default
    environment:
      WP_TARGET_HOST: wordpress
      WP_TARGET_PORT: 80
      WP_PROXY_HOST: localhost
      WP_PROXY_ADDR: 0.0.0.0
      WP_PROXY_PORT: 5001
    ports:
      - 5001:5001
    networks:
      - wp

volumes:
  db:
  theme:

networks:
  db:
  wp:
