mysql:
  image: mariadb
  environment:
    MYSQL_ROOT_PASSWORD: password
wordpress:
  image: wordpress
  volumes:
    - ./plugins:/var/www/html/wp-content/plugins
    - ./themes:/var/www/html/wp-content/themes
  ports:
    - 8080:80
  environment:
    WORDPRESS_DB_PASSWORD: password
  links:
    - mysql
